name = glass_tools
title = Glass Tools
description = Adds fragile glass tools.
optional_depends = default, vessels, mcl_core, mcl_sounds
supported_games = minetest_game, mineclone2, mineclonia
min_minetest_version = 5.8.0
author = gtzi203
